/*******************************************************************************
 * Copyright (c) 2012 EclipseSource and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    EclipseSource - initial API and implementation
 ******************************************************************************/
package com.eclipsesource.train.dashboard.internal;

import java.util.Calendar;
import java.util.Date;


public class TrainServiceKey {
  
  private final int year;
  private final int month;
  private final int day;

  public TrainServiceKey( Date date ) {
    Calendar calendar = Calendar.getInstance();
    calendar.setTime( date );
    year = calendar.get( Calendar.YEAR );
    month = calendar.get( Calendar.MONTH );
    day = calendar.get( Calendar.DAY_OF_MONTH );
    ensureValidKey();
  }

  private void ensureValidKey() {
    Calendar calendar = Calendar.getInstance();
    calendar.setTime( new Date() );
    int currentYear = calendar.get( Calendar.YEAR );
    int currentMonth = calendar.get( Calendar.MONTH );
    int currentDay = calendar.get( Calendar.DAY_OF_MONTH );
    if( year == currentYear && month == currentMonth && day > currentDay ) {
      throw new IllegalArgumentException( "Could not create key for future dates" );
    }
  }
  
  @Override
  public String toString() {
    return year + "-" + intToString( month ) + "-" + intToString( day );
  }
  
  private String intToString( int number ) {
    String result;
    if( number < 10 ) {
      result = "0" + number;
    } else {
      result = String.valueOf( number );
    }
    return result;
  }

  //generated by Eclipse, ugly but sufficient for the moment
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + day;
    result = prime * result + month;
    result = prime * result + year;
    return result;
  }

  @Override
  public boolean equals( Object obj ) {
    if( this == obj )
      return true;
    if( obj == null )
      return false;
    if( getClass() != obj.getClass() )
      return false;
    TrainServiceKey other = ( TrainServiceKey )obj;
    if( day != other.day )
      return false;
    if( month != other.month )
      return false;
    if( year != other.year )
      return false;
    return true;
  }
  
}
