/*******************************************************************************
 * Copyright (c) 2012 EclipseSource and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    EclipseSource - initial API and implementation
 ******************************************************************************/
package com.eclipsesource.train.dashboard.model;


public class Station {
  
  private double lat;
  private double lon;
  private String name;
  private int id;
  
  public double getLat() {
    return lat;
  }
  
  public double getLon() {
    return lon;
  }
  
  public String getName() {
    return name;
  }
  
  public int getId() {
    return id;
  }
  
  @Override
  public String toString() {
    return id + ": " + name + "(lat: " + lat + ", lon: " + lon + ")";
  }

  // generated by Eclipse, ugly but sufficient for the moment
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + id;
    long temp;
    temp = Double.doubleToLongBits( lat );
    result = prime * result + ( int )( temp ^ ( temp >>> 32 ) );
    temp = Double.doubleToLongBits( lon );
    result = prime * result + ( int )( temp ^ ( temp >>> 32 ) );
    result = prime * result + ( ( name == null )
                                                ? 0
                                                : name.hashCode() );
    return result;
  }

  @Override
  public boolean equals( Object obj ) {
    if( this == obj )
      return true;
    if( obj == null )
      return false;
    if( getClass() != obj.getClass() )
      return false;
    Station other = ( Station )obj;
    if( id != other.id )
      return false;
    if( Double.doubleToLongBits( lat ) != Double.doubleToLongBits( other.lat ) )
      return false;
    if( Double.doubleToLongBits( lon ) != Double.doubleToLongBits( other.lon ) )
      return false;
    if( name == null ) {
      if( other.name != null )
        return false;
    } else if( !name.equals( other.name ) )
      return false;
    return true;
  }
  
}
