/*******************************************************************************
 * Copyright (c) 2012 EclipseSource and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    EclipseSource - initial API and implementation
 ******************************************************************************/
package com.eclipsesource.train.dashboard.model;


public class StationInfo {
  
  private int arrival;
  private int departure;
  private int station_id;
  private int delay;
  private String delay_cause;
  
  public int getArrival() {
    return arrival;
  }
  
  public int getDeparture() {
    return departure;
  }
  
  public int getStationId() {
    return station_id;
  }
  
  public int getDelay() {
    return delay;
  }
  
  public String getDelayCause() {
    return delay_cause;
  }
  
  @Override
  public String toString() {
    StringBuilder stringBuilder = new StringBuilder();
    stringBuilder.append( station_id + ": " );
    stringBuilder.append( "arrival=" + arrival );
    stringBuilder.append( ", departure=" + departure );
    if( delay > 0 ) {
      stringBuilder.append( ", delay=" + delay );
      if( delay_cause != null ) {
        stringBuilder.append( ", delayCause=" + delay_cause );
      }
    }
    return stringBuilder.toString();
  }

  // generated by Eclipse, ugly but sufficient for the moment
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + arrival;
    result = prime * result + delay;
    result = prime * result + ( ( delay_cause == null )
                                                       ? 0
                                                       : delay_cause.hashCode() );
    result = prime * result + departure;
    result = prime * result + station_id;
    return result;
  }

  @Override
  public boolean equals( Object obj ) {
    if( this == obj )
      return true;
    if( obj == null )
      return false;
    if( getClass() != obj.getClass() )
      return false;
    StationInfo other = ( StationInfo )obj;
    if( arrival != other.arrival )
      return false;
    if( delay != other.delay )
      return false;
    if( delay_cause == null ) {
      if( other.delay_cause != null )
        return false;
    } else if( !delay_cause.equals( other.delay_cause ) )
      return false;
    if( departure != other.departure )
      return false;
    if( station_id != other.station_id )
      return false;
    return true;
  }
  
}
